name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.13'
      # https://github.com/actions/setup-python/issues/330
      - id: python_cache
        uses: actions/cache@v3
        with:
          path: venv
          key:
            pip-${{ steps.setup_python.outputs.python-version }}-${{
            hashFiles('./src/requirements.txt') }}

      - if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          pip install -r ./typos_tool/requirements.txt
          cd ./typos_tool && pip install .

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          check-file: ./src/requirements.txt

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.check-output }}"
